account:
    name: "Playground"

users:
    - account: "Playground"
      email: "admin@sequinstream.com"
      password: "sequinpassword!"

databases:
    - name: "app-database"
      username: "user"
      password: "password"
      hostname: "postgres"
      database: "app"
      port: 5432
      slot_name: "sequin_slot"
      publication_name: "sequin_pub"
